## Web Scraping

In [1]:
!pip install bs4
!pip install lxml==4.6.4
!pip install html5lib==1.1
!pip install requests==2.26.0

Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: beautifulsoup4 in c:\users\ciwar\appdata\roaming\python\python310\site-packages (from bs4) (4.12.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\ciwar\appdata\roaming\python\python310\site-packages (from beautifulsoup4->bs4) (2.4)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1266 sha256=4b68296e77e9aab92830cf1f512edab3e79ab6edbe93ad0475d5c1576472be94
  Stored in directory: c:\users\ciwar\appdata\local\pip\cache\wheels\25\42\45\b773edc52acb16cd2db4cf1a0b47117e2f69bb4eb300ed0e70
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1
Collecting lxml==4.6.4
  Downloading lxml-4.6.4-cp310-cp310-win_amd64.whl (3.5 MB)
     ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.5 MB 653.6 kB/s eta 0:00:06
     - -------------------------------------- 0.1/3.5 MB 1.2 MB/s eta 0:00:03
     -- ------------------------------------- 0.2/3.5 MB 1.3 MB/s eta 0:00:03
     -- ------------------------------------- 0.3/3.5 MB 1.4 MB/s eta 0:00:03
     ---- ----------------------------------- 0.4/3.5 MB 1.5 MB/s eta 0:00:03
     ----- ---------------------------------- 0.5/3.5 MB 1.8 MB/s eta 0:00:02
     ------ --------------------------------- 0.5/3.5 MB 1.6 MB/s eta 0:00:02
     ------ --------------------------------- 0.5/3.5 MB 1.6 MB/s eta 0:00:02
     ------ --------------------------------- 0.6/3.5 MB 1.3 MB/s eta 0:00:03
     ------- -------------------------------- 0.7/3.5 MB 1.4 MB/s eta 0:00:03
     ------- -------------------------------- 0.7/3.5 MB 1.4 MB/s eta 0:00:02
     -------- ------------------------------- 0.7/3.5 MB 1.4 MB/s eta 0:00:03
     --------- ------------------------------ 0.8/3.5 MB 1.4 MB/s eta 0:00:02
     --------- ------------------------------ 0.8/3.5 MB 1.4 MB/s eta 0:00:02
     ---------- ----------------------------- 0.9/3.5 MB 1.3 MB/s eta 0:00:03
     ----------- ---------------------------- 1.0/3.5 MB 1.4 MB/s eta 0:00:02
     ------------ --------------------------- 1.1/3.5 MB 1.5 MB/s eta 0:00:02
     ------------- -------------------------- 1.2/3.5 MB 1.5 MB/s eta 0:00:02
     -------------- ------------------------- 1.2/3.5 MB 1.4 MB/s eta 0:00:02
     -------------- ------------------------- 1.3/3.5 MB 1.4 MB/s eta 0:00:02
     ---------------- ----------------------- 1.5/3.5 MB 1.5 MB/s eta 0:00:02
     ------------------- -------------------- 1.7/3.5 MB 1.7 MB/s eta 0:00:02
     ---------------------- ----------------- 2.0/3.5 MB 1.9 MB/s eta 0:00:01
     ------------------------- -------------- 2.2/3.5 MB 2.0 MB/s eta 0:00:01
     --------------------------- ------------ 2.4/3.5 MB 2.1 MB/s eta 0:00:01
     ------------------------------ --------- 2.7/3.5 MB 2.2 MB/s eta 0:00:01
     -------------------------------- ------- 2.8/3.5 MB 2.3 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.1/3.5 MB 2.4 MB/s eta 0:00:01
     ----------------------------------- ---- 3.2/3.5 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  3.5/3.5 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  3.5/3.5 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------  3.5/3.5 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------  3.5/3.5 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------- 3.5/3.5 MB 2.0 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-4.6.4
Collecting html5lib==1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ---------------------------------------- 0.0/112.2 kB ? eta -:--:--
     ---------------------------------- --- 102.4/112.2 kB 6.1 MB/s eta 0:00:01
     -------------------------------------- 112.2/112.2 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: webencodings in c:\users\ciwar\appdata\roaming\python\python310\site-packages (from html5lib==1.1) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\ciwar\appdata\roaming\python\python310\site-packages (from html5lib==1.1) (1.16.0)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Collecting requests==2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     ---------------------------------------- 0.0/62.3 kB ? eta -:--:--
     ------------------ ------------------- 30.7/62.3 kB 660.6 kB/s eta 0:00:01
     ---------------------------------------  61.4/62.3 kB 1.1 MB/s eta 0:00:01
     -------------------------------------- 62.3/62.3 kB 416.1 kB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ciwar\appdata\local\programs\python\python310\lib\site-packages (from requests==2.26.0) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ciwar\appdata\roaming\python\python310\site-packages (from requests==2.26.0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ciwar\appdata\local\programs\python\python310\lib\site-packages (from requests==2.26.0) (2022.12.7)
Installing collected packages: charset-normalizer, requests
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.1.0
    Uninstalling charset-normalizer-3.1.0:
      Successfully uninstalled charset-normalizer-3.1.0
  Attempting uninstall: requests
    Found existing installation: requests 2.28.2
    Uninstalling requests-2.28.2:
      Successfully uninstalled requests-2.28.2
Successfully installed charset-normalizer-2.0.12 requests-2.26.0

In [3]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests # this module helps us to download a web page

<h2 id="DSCW">Downloading And Scraping The Contents Of A Web Page</h2>

In [2]:
url = "http://www.ibm.com"

Use <code>get</code> to download the contents of the webpage in text format and store in a variable called <code>data</code>:

In [4]:
data = requests.get(url).text

We create a <code>BeautifulSoup</code> object using the <code>BeautifulSoup</code> constructor

In [5]:
soup = BeautifulSoup(data, "html.parser")

Scrape all links

In [6]:
for link in soup.find_all('a', href=True):
    print(link.get('href'))

https://www.ibm.com/thought-leadership/institute-business-value/c-suite-study/cdo
https://www.ibm.com/about
https://www.ibm.com/consulting/?lnk=flathl
https://www.ibm.com/consulting/strategy/?lnk=flathl
https://www.ibm.com/consulting/ibmix?lnk=flathl
https://www.ibm.com/consulting/technology/
https://www.ibm.com/consulting/operations/?lnk=flathl
https://www.ibm.com/strategic-partnerships
https://www.ibm.com/employment/?lnk=flatitem
https://www.ibm.com/impact
https://research.ibm.com/
https://www.ibm.com/

## Scrape  all images  Tags

In [8]:
for link in soup.find_all('img'):
    print(link)
    print(link.get('src'))

<img alt="Grid of diverse group of professionals" aria-describedby="bx--image-1" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57bcbf324/dotcom-1-overview.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57bcbf324/dotcom-1-overview.jpg.global.sr_16x9.jpg
<img alt="professional pointing to a chart" aria-describedby="bx--image-2" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57c4bf381/0935e0d55846b9ec_dotcom-2-strategy.jpg.global.m_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57c4bf381/0935e0d55846b9ec_dotcom-2-strategy.jpg.global.m_16x9.jpg
<img alt="two professionals working with a whiteboard outdoors" aria-describedby="bx--image-3" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57c4bf382/0656655b47a3af8b_dotcom-3-experience.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57c4bf382/0656655b47a3af8b_dotcom-3-experience.jpg.global.sr_16x9.jpg
<img alt="professionals working with a sticky notes on a whiteboard" aria-describedby="bx--image-4" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57c4bf383/08f9513598a70746_dotcom-4-technology.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57c4bf383/08f9513598a70746_dotcom-4-technology.jpg.global.sr_16x9.jpg
<img alt="professionals having a conversation in an office" aria-describedby="bx--image-5" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57c4bf380/0935e0d55846b9e4_dotcom-5-operations.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57c4bf380/0935e0d55846b9e4_dotcom-5-operations.jpg.global.sr_16x9.jpg
<img alt="group of professionals walking down stairs outdoors" aria-describedby="bx--image-6" class="bx--image__img" src="https://1.dam.s81c.com/p/0aac9cf57c4bf384/064e0139f5a3aa3f_dotcom-6-partners.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0aac9cf57c4bf384/064e0139f5a3aa3f_dotcom-6-partners.jpg.global.sr_16x9.jpg

## Scrape data from HTML tables

In [9]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/HTMLColorCodes.html"

Before proceeding to scrape a web site, you need to examine the contents, and the way data is organized on the website. Open the above url in your browser and check how many rows and columns are there in the color table.

In [10]:
# get the contents of the webpage in text format and store in a variable called data
data = requests.get(url).text

In [11]:
data

'<html>\n   <body>\n      <h1>Partital List  of HTML5 Supported Colors</h1>\n<table border ="1" class="main-table">\n   <tr>\n      <td>Number </td>\n      <td>Color</td>\n      <td>Color Name</td>\n      <td>Hex Code<br>#RRGGBB</td>\n      <td>Decimal Code<br>(R,G,B)</td>\n   </tr>\n   <tr>\n      <td>1</td>\n      <td style="background:lightsalmon;">&nbsp;</td>\n      <td>lightsalmon</td>\n      <td>#FFA07A</td>\n      <td>rgb(255,160,122)</td>\n   </tr>\n   <tr>\n      <td>2</td>\n      <td style="background:salmon;">&nbsp;</td>\n      <td>salmon</td>\n      <td>#FA8072</td>\n      <td>rgb(250,128,114)</td>\n   </tr>\n   <tr>\n      <td>3</td>\n      <td style="background:darksalmon;">&nbsp;</td>\n      <td>darksalmon</td>\n      <td>#E9967A</td>\n      <td>rgb(233,150,122)</td>\n   </tr>\n   <tr>\n      <td>4</td>\n      <td style="background:lightcoral;">&nbsp;</td>\n      <td>lightcoral</td>\n      <td>#F08080</td>\n      <td>rgb(240,128,128)</td>\n   </tr>\n   <tr>\n      <td>5</td>\n      <td style="background:coral;">&nbsp;</td>\n      <td>coral</td>\n      <td>#FF7F50</td>\n      <td>rgb(255,127,80)</td>\n   </tr>\n   <tr>\n      <td>6</td>\n      <td style="background:tomato;">&nbsp;</td>\n      <td>tomato</td>\n      <td>#FF6347</td>\n      <td>rgb(255,99,71)</td>\n   </tr>\n   <tr>\n      <td>7</td>\n      <td style="background:orangered;">&nbsp;</td>\n      <td>orangered</td>\n      <td>#FF4500</td>\n      <td>rgb(255,69,0)</td>\n   </tr>\n   <tr>\n      <td>8</td>\n      <td style="background:gold;">&nbsp;</td>\n      <td>gold</td>\n      <td>#FFD700</td>\n      <td>rgb(255,215,0)</td>\n   </tr>\n   <tr>\n      <td>9</td>\n      <td style="background:orange;">&nbsp;</td>\n      <td>orange</td>\n      <td>#FFA500</td>\n      <td>rgb(255,165,0)</td>\n   </tr>\n   <tr>\n      <td>10</td>\n      <td style="background:darkorange;">&nbsp;</td>\n      <td>darkorange</td>\n      <td>#FF8C00</td>\n      <td>rgb(255,140,0)</td>\n   </tr>\n   <tr>\n      <td>11</td>\n      <td style="background:lightyellow;">&nbsp;</td>\n      <td>lightyellow</td>\n      <td>#FFFFE0</td>\n      <td>rgb(255,255,224)</td>\n   </tr>\n   <tr>\n      <td>12</td>\n      <td style="background:lemonchiffon;">&nbsp;</td>\n      <td>lemonchiffon</td>\n      <td>#FFFACD</td>\n      <td>rgb(255,250,205)</td>\n   </tr>\n   <tr>\n      <td>13</td>\n      <td style="background:papayawhip;">&nbsp;</td>\n      <td>papayawhip</td>\n      <td>#FFEFD5</td>\n      <td>rgb(255,239,213)</td>\n   </tr>\n   <tr>\n      <td>14</td>\n      <td style="background:moccasin;">&nbsp;</td>\n      <td>moccasin</td>\n      <td>#FFE4B5</td>\n      <td>rgb(255,228,181)</td>\n   </tr>\n   <tr>\n      <td>15</td>\n      <td style="background:peachpuff;">&nbsp;</td>\n      <td>peachpuff</td>\n      <td>#FFDAB9</td>\n      <td>rgb(255,218,185)</td>\n   </tr>\n   <tr>\n      <td>16</td>\n      <td style="background:palegoldenrod;">&nbsp;</td>\n      <td>palegoldenrod</td>\n      <td>#EEE8AA</td>\n      <td>rgb(238,232,170)</td>\n   </tr>\n   <tr>\n      <td>17</td>\n      <td style="background:khaki;">&nbsp;</td>\n      <td>khaki</td>\n      <td>#F0E68C</td>\n      <td>rgb(240,230,140)</td>\n   </tr>\n   <tr>\n      <td>18</td>\n      <td style="background:darkkhaki;">&nbsp;</td>\n      <td>darkkhaki</td>\n      <td>#BDB76B</td>\n      <td>rgb(189,183,107)</td>\n   </tr>\n   <tr>\n      <td>19</td>\n      <td style="background:yellow;">&nbsp;</td>\n      <td>yellow</td>\n      <td>#FFFF00</td>\n      <td>rgb(255,255,0)</td>\n   </tr>\n   <tr>\n      <td>20</td>\n      <td style="background:lawngreen;">&nbsp;</td>\n      <td>lawngreen</td>\n      <td>#7CFC00</td>\n      <td>rgb(124,252,0)</td>\n   </tr>\n   <tr>\n      <td>21</td>\n      <td style="background:chartreuse;">&nbsp;</td>\n      <td>chartreuse</td>\n      <td>#7FFF00</td>\n      <td>rgb(127,255,0)</td>\n   </tr>\n   <tr>\n      <td>22</td>\n      <td style="background:limegreen;">&nbsp;</td>\n      <td>limegreen</td>\n      <td>#32CD32</td>\n      <td>rgb(50,205,50)</td>\n   </tr>\n   <tr>\n      <td>23</td>\n      <td style="background:lime;">&nbsp;</td>\n      <td>lime</td>\n      <td>#00FF00</td>\n      <td>rgb(0.255.0)</td>\n   </tr>\n   <tr>\n      <td>24</td>\n      <td style="background:forestgreen;">&nbsp;</td>\n      <td>forestgreen</td>\n      <td>#228B22</td>\n      <td>rgb(34,139,34)</td>\n   </tr>\n   <tr>\n      <td>25</td>\n      <td style="background:green;">&nbsp;</td>\n      <td>green</td>\n      <td>#008000</td>\n      <td>rgb(0,128,0)</td>\n   </tr>\n   <tr>\n      <td>26</td>\n      <td style="background:powderblue;">&nbsp;</td>\n      <td>powderblue</td>\n      <td>#B0E0E6</td>\n      <td>rgb(176,224,230)</td>\n   </tr>\n   <tr>\n      <td>27</td>\n      <td style="background:lightblue;">&nbsp;</td>\n      <td>lightblue</td>\n      <td>#ADD8E6</td>\n      <td>rgb(173,216,230)</td>\n   </tr>\n   <tr>\n      <td>28</td>\n      <td style="background:lightskyblue;">&nbsp;</td>\n      <td>lightskyblue</td>\n      <td>#87CEFA</td>\n      <td>rgb(135,206,250)</td>\n   </tr>\n   <tr>\n      <td>29</td>\n      <td style="background:skyblue;">&nbsp;</td>\n      <td>skyblue</td>\n      <td>#87CEEB</td>\n      <td>rgb(135,206,235)</td>\n   </tr>\n   <tr>\n      <td>30</td>\n      <td style="background:deepskyblue;">&nbsp;</td>\n      <td>deepskyblue</td>\n      <td>#00BFFF</td>\n      <td>rgb(0,191,255)</td>\n   </tr>\n   <tr>\n      <td>31</td>\n      <td style="background:lightsteelblue;">&nbsp;</td>\n      <td>lightsteelblue</td>\n      <td>#B0C4DE</td>\n      <td>rgb(176,196,222)</td>\n   </tr>\n   <tr>\n      <td>32</td>\n      <td style="background:dodgerblue;">&nbsp;</td>\n      <td>dodgerblue</td>\n      <td>#1E90FF</td>\n      <td>rgb(30,144,255)</td>\n   </tr>\n</table>\n   </body>\n</html>'

In [12]:
soup = BeautifulSoup(data, "html.parser")

In [13]:
#find a html table in the web page
table = soup.find('table')

In [18]:
#Get all rows from the table
for row in table.find_all('tr'):
    # Get all columns in each row.
    cols = row.find_all('td')
    color_code = cols[3].string
    color_name = cols[2].string
    print("{}---->{}".format(color_code, color_name))

None---->Color Name
#FFA07A---->lightsalmon
#FA8072---->salmon
#E9967A---->darksalmon
#F08080---->lightcoral
#FF7F50---->coral
#FF6347---->tomato
#FF4500---->orangered
#FFD700---->gold
#FFA500---->orange
#FF8C00---->darkorange
#FFFFE0---->lightyellow
#FFFACD---->lemonchiffon
#FFEFD5---->papayawhip
#FFE4B5---->moccasin
#FFDAB9---->peachpuff
#EEE8AA---->palegoldenrod
#F0E68C---->khaki
#BDB76B---->darkkhaki
#FFFF00---->yellow
#7CFC00---->lawngreen
#7FFF00---->chartreuse
#32CD32---->limegreen
#00FF00---->lime
#228B22---->forestgreen
#008000---->green
#B0E0E6---->powderblue
#ADD8E6---->lightblue
#87CEFA---->lightskyblue
#87CEEB---->skyblue
#00BFFF---->deepskyblue
#B0C4DE---->lightsteelblue
#1E90FF---->dodgerblue

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and Pandas

In [19]:
import pandas as pd

In [20]:
url = "https://en.wikipedia.org/wiki/World_population"

Before proceeding to scrape a web site, you need to examine the contents, and the way data is organized on the website. Open the above url in your browser and check the tables on the webpage.

In [21]:
data = requests.get(url).text

In [22]:
soup = BeautifulSoup(data, "html.parser")

In [23]:
tables = soup.find_all('table')

In [24]:
len(tables)

24

Assume that we are looking for the `10 most densly populated countries` table, we can look through the tables list and find the right one we are look for based on the data in each table or we can search for the table name if it is in the table but this option might not always work.

In [25]:
for index, table in enumerate(tables):
    if("10 most densely populated countries" in str(table)):
        table_index = index
print(table_index)

4

See if you can locate the table name of the table, `10 most densly populated countries`, below.

In [26]:
print(tables[table_index].prettify())

<table class="wikitable sortable" style="text-align:right">
 <caption>
  10 most densely populated countries
  <small>
   (with population above 5 million)
  </small>
  <sup class="reference" id="cite_ref-:10_107-0">
   <a href="#cite_note-:10-107">
    [102]
   </a>
  </sup>
 </caption>
 <tbody>
  <tr>
   <th scope="col">
    Rank
   </th>
   <th scope="col">
    Country
   </th>
   <th scope="col">
    Population
   </th>
   <th scope="col">
    Area
    <br/>
    <small>
     (km
     <sup>
      2
     </sup>
     )
    </small>
   </th>
   <th scope="col">
    Density
    <br/>
    <small>
     (pop/km
     <sup>
      2
     </sup>
     )
    </small>
   </th>
  </tr>
  <tr>
   <td>
    1
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/35px-Flag_of_Singapore.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/45px-Flag_of_Singapore.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Singapore" title="Singapore">
     Singapore
    </a>
   </td>
   <td>
    5,921,231
   </td>
   <td>
    719
   </td>
   <td>
    8,235
   </td>
  </tr>
  <tr>
   <td>
    2
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Bangladesh" title="Bangladesh">
     Bangladesh
    </a>
   </td>
   <td>
    165,650,475
   </td>
   <td>
    148,460
   </td>
   <td>
    1,116
   </td>
  </tr>
  <tr>
   <td>
    3
   </td>
   <td align="left">
    <p>
     <span class="flagicon">
      <img alt="" class="thumbborder" data-file-height="216" data-file-width="432" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/35px-Flag_of_Palestine.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/46px-Flag_of_Palestine.svg.png 2x" width="23"/>
     </span>
     <a href="/wiki/State_of_Palestine" title="State of Palestine">
      Palestine
     </a>
     <sup class="reference" id="cite_ref-108">
      <a href="#cite_note-108">
       [103]
      </a>
     </sup>
    </p>
   </td>
   <td>
    5,223,000
   </td>
   <td>
    6,025
   </td>
   <td>
    867
   </td>
  </tr>
  <tr>
   <td>
    4
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Taiwan" title="Taiwan">
     Taiwan
    </a>
   </td>
   <td>
    23,580,712
   </td>
   <td>
    35,980
   </td>
   <td>
    655
   </td>
  </tr>
  <tr>
   <td>
    5
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/South_Korea" title="South Korea">
     South Korea
    </a>
   </td>
   <td>
    51,844,834
   </td>
   <td>
    99,720
   </td>
   <td>
    520
   </td>
  </tr>
  <tr>
   <td>
    6
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/35px-Flag_of_Lebanon.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/45px-Flag_of_Lebanon.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Lebanon" title="Lebanon">
     Lebanon
    </a>
   </td>
   <td>
    5,296,814
   </td>
   <td>
    10,400
   </td>
   <td>
    509
   </td>
  </tr>
  <tr>
   <td>
    7
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/35px-Flag_of_Rwanda.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/45px-Flag_of_Rwanda.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Rwanda" title="Rwanda">
     Rwanda
    </a>
   </td>
   <td>
    13,173,730
   </td>
   <td>
    26,338
   </td>
   <td>
    500
   </td>
  </tr>
  <tr>
   <td>
    8
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/35px-Flag_of_Burundi.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/46px-Flag_of_Burundi.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Burundi" title="Burundi">
     Burundi
    </a>
   </td>
   <td>
    12,696,478
   </td>
   <td>
    27,830
   </td>
   <td>
    456
   </td>
  </tr>
  <tr>
   <td>
    9
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="900" data-file-width="1350" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/India" title="India">
     India
    </a>
   </td>
   <td>
    1,389,637,446
   </td>
   <td>
    3,287,263
   </td>
   <td>
    423
   </td>
  </tr>
  <tr>
   <td>
    10
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Netherlands" title="Netherlands">
     Netherlands
    </a>
   </td>
   <td>
    17,400,824
   </td>
   <td>
    41,543
   </td>
   <td>
    419
   </td>
  </tr>
 </tbody>
</table>

In [27]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

for row in tables[table_index].tbody.find_all('tr'):
    col = row.find_all('td')
    if(col != []):
        rank = col[0].text
        country = col[1].text
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()
        population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)

population_data

C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)
C:\Users\ciwar\AppData\Local\Temp\ipykernel_7268\3764171498.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  population_data = population_data.append({"Rank": rank, "Country": country, "Population": population, "Area": area, "Density": density}, ignore_index=True)

  Rank                Country     Population       Area Density
0    1              Singapore      5,921,231        719   8,235
1    2             Bangladesh    165,650,475    148,460   1,116
2    3  \n Palestine[103]\n\n      5,223,000      6,025     867
3    4                 Taiwan     23,580,712     35,980     655
4    5            South Korea     51,844,834     99,720     520
5    6                Lebanon      5,296,814     10,400     509
6    7                 Rwanda     13,173,730     26,338     500
7    8                Burundi     12,696,478     27,830     456
8    9                  India  1,389,637,446  3,287,263     423
9   10            Netherlands     17,400,824     41,543     419

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and read_html

Using the same `url`, `data`, `soup`, and `tables` object as in the last section we can use the `read_html` function to create a DataFrame.

Remember the table we need is located in `tables[table_index]`

We can now use the `pandas` function `read_html` and give it the string version of the table as well as the `flavor` which is the parsing engine `bs4`.

In [32]:
pd.read_html(str(tables[5]), flavor='bs4')

[   Rank         Country  Population  Area (km2)  Density (pop/km2)  \
 0     1           India  1389637446     3287263                423
 1     2        Pakistan   242923845      796095                305
 2     3      Bangladesh   165650475      148460               1116
 3     4           Japan   124214766      377915                329
 4     5     Philippines   114597229      300000                382
 5     6         Vietnam   103808319      331210                313
 6     7  United Kingdom    67791400      243610                278
 7     8     South Korea    51844834       99720                520
 8     9          Taiwan    23580712       35980                655
 9    10       Sri Lanka    23187516       65610                353

   Population trend[citation needed]
 0                           Growing
 1                   Rapidly growing
 2                           Growing
 3                    Declining[104]
 4                           Growing
 5                           Growing
 6                           Growing
 7                            Steady
 8                            Steady
 9                           Growing  ]

The function `read_html` always returns a list of DataFrames so we must pick the one we want out of the list.

In [35]:
population_data_read_html = pd.read_html(str(tables[5]), flavor='bs4')[0]
population_data_read_html

,Rank,Country,Population,Area (km2),Density (pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

## Scrape data from HTML tables into a DataFrame using read_html

We can also use the `read_html` function to directly get DataFrames from a `url`.

In [36]:
dataframe_list = pd.read_html(url, flavor='bs4')

We can see there are 25 DataFrames just like when we used `find_all` on the `soup` object.

In [37]:
len(dataframe_list)

24

Finally we can pick the DataFrame we need out of the list.

In [38]:
dataframe_list[5]

,Rank,Country,Population,Area (km2),Density (pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

We can also use the `match` parameter to select the specific table we want. If the table contains a string matching the text it will be read.

In [40]:
pd.read_html(url, match="10 most densely populated countries", flavor='bs4')[0]

   Rank         Country  Population  Area (km2)  Density (pop/km2)
0     1       Singapore     5921231         719               8235
1     2      Bangladesh   165650475      148460               1116
2     3  Palestine[103]     5223000        6025                867
3     4          Taiwan    23580712       35980                655
4     5     South Korea    51844834       99720                520
5     6         Lebanon     5296814       10400                509
6     7          Rwanda    13173730       26338                500
7     8         Burundi    12696478       27830                456
8     9           India  1389637446     3287263                423
9    10     Netherlands    17400824       41543                419